config/routes.rb
Gig::Application.routes.draw do
  root :to => "users#index"

  get "/login" => redirect("/auth/github"), :as => :login

  controller :sessions do
    get "auth/:provider/callback" => :callback
    get "auth/failure"            => :failure
    delete "logout"               => :destroy, :as => :logout
  end

  resource :cache, :only => :create

  resources :users, :only => [:index, :show], :path => "" do
    resources :entries, :except => :index, :path => "", :constraints => { :id => /.+/ }
  end
end

app/models/entry.rb
class Entry
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_reader :attributes

  def self.new_with_name(attributes)
    if attributes[:name]
      attributes[:path] = "#{attributes.delete(:name)}.md"
    end
    new(attributes)
  end

  def initialize(attributes = {})
    @attributes = attributes
  end

  def save
    if valid?
      user.commit(self)
      user.clear_cache(self)
      persisted!
      self
    else
      false
    end
  end

  def valid?
    name.present?
  end

  def id
    filename
  end

  def content
    @attributes[:content]
  end

  def path
    @attributes[:path]
  end

  def persisted?
    @attributes[:persisted]
  end

  def time
    @attributes[:time]
  end

  def nickname
    @attributes[:nickname]
  end

  def persisted!
    @attributes[:persisted] = true
  end

  def pathname
    @pathname ||= Pathname.new(path || "")
  end

  def filename
    pathname.basename.to_s
  end

  def name
    pathname.basename(".*").to_s.gsub(/^\..*/, "")
  end
  alias_method :title, :name

  def date
    time.localtime.to_date
  end

  def user
    @user ||= User.find_by_nickname!(nickname)
  end

  def to_param
    filename
  end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/settings.yml"
  namespace Rails.env
end

app/models/user.rb
# User is a model for an owner of this blog and we assume there is only 1 user.
# The responsibility to attach Settings.github.entries_path belongs to User class.
class User < ActiveRecord::Base
  attr_accessible :nickname, :provider, :token, :uid

  validates :nickname, :provider, :uid, :token, :presence => true
  validates :uid, :presence => true, :uniqueness => { :scope => :provider }

  delegate(
    :db_repository_name,
    :db_repository_owner,
    :entries_path,
    :hook_url,
    :repository,
    :to => "Settings.github"
  )

  scope :alphabetical, lambda { order("nickname DESC") }

  class << self
    def admin
      User.find_by_nickname(Settings.github.nickname)
    end

    def find_or_create_from_auth(auth)
      find_from_auth(auth) || create_from_auth(auth)
    end

    private

    def find_from_auth(auth)
      attributes = auth.slice("provider", "uid")
      where(attributes).first
    end

    def create_from_auth(auth)
      create(
        :nickname => auth["info"]["nickname"],
        :provider => auth["provider"],
        :token    => auth["credentials"]["token"],
        :uid      => auth["uid"],
      ).tap(&:create_repository)
    end

    # Meta utility method to cache method's returned value
    # For instance: returned value of #entries will be cached in 1.day with "entries" as cache key
    #  cache_method(:entries, 1.day) { "entries" }
    def cache_method(method_name, expires_in, &cache_key)
      define_method("#{method_name}_with_cache") do |*args|
        Rails.cache.fetch instance_exec(*args, &cache_key), :expires_in => expires_in do
          __send__("#{method_name}_without_cache", *args)
        end
      end
      alias_method_chain method_name, :cache
    end
  end

  def commit(entry)
    github_client.update("#{entries_path}/#{entry.filename}", entry.content)
  end

  def entries
    list = github_client.list(entries_path)
    list.map {|attributes| Entry.new(attributes) }
  end

  def entry(entry_name)
    if attributes = github_client.find("#{entries_path}/#{entry_name}")
      Entry.new(attributes)
    end
  end

  def build_entry(attributes = {})
    Entry.new_with_name attributes.merge(:nickname => nickname)
  end

  def destroy_entry(entry_name)
    github_client.delete("#{entries_path}/#{entry_name}")
  end

  def create_repository
    github_client.fork(db_repository_owner, db_repository_name, repository)
    github_client.hook(nickname, repository, hook_url)
  end

  def to_param
    nickname
  end

  def clear_cache(filename)
    Rails.cache.delete("#{nickname}/#{entries_path}/#{filename}")
    Rails.cache.delete("#{nickname}/#{entries_path}")
  end

  private

  def github_client
    @github_client ||= GithubClient.new(
      :nickname     => nickname,
      :repository   => repository,
      :token        => token
    )
  end

  # cache_method(:entries, 1.day) { "#{nickname}/#{entries_path}" }
  cache_method(:entry, 1.day) {|filename| "#{nickname}/#{entries_path}/#{filename}" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  NotFound = Class.new(StandardError)

  rescue_from ActiveRecord::RecordNotFound, NotFound, :with => :render_not_found

  helper_method :current_user, :logged_in?, :author

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end

  def logged_in?
    !!current_user
  end

  def render_not_found
    render "public/404", :layout => false, :status => 404
  end

  def require_login
    redirect_to login_path unless logged_in?
  end
end

app/controllers/caches_controller.rb
class CachesController < ApplicationController
  before_filter :require_github, :only => :create

  def create
    payload = JSON.parse(params[:payload])

    nickname = payload["repository"]["owner"]["name"]
    commits  = payload["commits"]
    user     = User.find_by_nickname!(nickname)
    paths    = commits.map {|commit| commit.values_at("added", "modified", "removed") }.flatten
    paths.each do |path|
      filename = File.basename(path)
      user.clear_cache(filename)
      user.entry(filename)
    end
    user.entries if paths.any?

    head 200
  end

  private

  def require_github
    head 400 unless github_request?
  end

  def github_request?
    request.user_agent.include?("GitHub Services Web Hook")
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :require_user
  before_filter :require_entry, :only => [:show, :edit, :update, :destroy]

  def new
    @entry = current_user.build_entry
    render :edit
  end

  def create
    @entry = current_user.build_entry(params[:entry])
    if @entry.save
      redirect_to user_entry_path(current_user, @entry)
    else
      render :edit
    end
  end

  def update
    if @entry.name == params[:entry][:name]
      current_user.destroy_entry(@entry.filename)
    end

    entry = current_user.build_entry(params[:entry])
    if entry.save
      redirect_to user_entry_path(current_user, @entry)
    else
      render :edit
    end
  end

  def destroy
    current_user.destroy_entry(@entry.filename)
    redirect_to @user
  end

  private

  def require_entry
    @entry = @user.entry(params[:id]) or raise NotFound
  end

  def require_user
    @user = User.find_by_nickname!(params[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    user = User.find_or_create_from_auth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to user
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :only => :show

  private

  def require_user
    @user = User.find_by_nickname!(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_action_classes
    %W[#{controller_name}_controller #{action_name}_action]
  end

  def link_to_with_icon(icon_type, path, options = {})
    link_to path, options do
      content_tag(:i, :class => "icon-#{icon_type}") {}
    end
  end

  def title_tag
    content_tag(:title) do
      if @entry.try(:name).present?
        "#{@entry.name} - GIG"
      else
        "GIG"
      end
    end
  end

  def request_new_entry?
      controller_name == "entries" && action_name == "new"
  end

  def show_welcome_message?
      !request_new_entry? && @user && @user.entries.empty?
  end

  class AbstractDecorator < SimpleDelegator
    include Rails.application.routes.url_helpers
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def decorate(args)
    case args
    when Enumerable
      args.map {|e| EntryDecorator.new(e) }
    else
      EntryDecorator.new(args)
    end
  end
end

app/views/entries/edit.html.slim
- entry = decorate(@entry)

- if entry.persisted?
  p.back
    = link_to [@user, entry] do
      i.icon-double-angle-left
      | back

p.note
  ' ( You can use
  = link_to "Markdown", "http://daringfireball.net/projects/markdown/", :target => "_blank"
  '  format )

= form_for([@user, entry]) do |f|
  .name
    = f.text_field :name, :placeholder => "title"

  .content
    = f.text_area :content, :placeholder => "body"

  .submit
    button.btn type="submit" title="OK" data-placement="bottom"
      i.icon-ok

app/views/entries/show.html.slim
- entry = decorate(@entry)

- if logged_in?
  .buttons
    = link_to_with_icon "pencil", entry.edit_path, :class => "btn", :title => "Edit"
    = link_to_with_icon "trash", [@user, entry], :method => :delete, :class => "btn", :confirm => "Are you sure to delete this entry?", :title => "Delete"
    = link_to_with_icon "github", entry.github_path, :class => "btn", :target => "_blank", :title => "GitHub"

article
  .header
    h1.title= link_to entry.title, [@user, entry]
    .info
      .date
        i.icon-calendar
        = entry.date
      .star-container

  .content= entry.rendered_content

app/views/layouts/application.html.slim
doctype html
html
  head
    = title_tag
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag "favicon.ico"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body class=current_action_classes
    header
      h1.title
        - if @user
          = link_to @user do
            i.icon-book
            = @user.nickname
        - else
          = link_to root_path do
            i.icon-github
            | GIG
      ul.links
        - if logged_in?
          li.link= link_to_with_icon "home", current_user, :title => "Home", "data-placement" => "bottom"
          - if show_welcome_message?
            li.link= link_to_with_icon "pencil", new_user_entry_path(current_user), :title => "New", 
              :rel => "welcome-message", "data-content" => "記事はここから書けます。最初の記事を投稿してみましょう！", "data-placement" => "bottom"
          - else  
            li.link= link_to_with_icon "pencil", new_user_entry_path(current_user), :title => "New", "data-placement" => "bottom"
          li.link= link_to_with_icon "signout", logout_path, :method => :delete, :title => "Logout", "data-placement" => "bottom"
        - else
          li.link= link_to_with_icon "signin", login_path, :title => "Login", "data-placement" => "bottom"


    .main
      = yield

    footer
      p
        = link_to "✘╹◡╹✘", "https://github.com/r7kamura/gig", :target => "_blank", :title => "GIG is an open sourced project"

app/views/users/index.html.slim
.section
  .caption
    h1 GIG
    h2 あるゆるブログとかに対する最高のソリューション
    = link_to login_path, :class => "btn btn-large btn-info" do
      i.icon-github
      | Get Started

.section
  h3
    i.icon-github
    | GIGとは？
  p
    | GIGはGitHubを利用したブログサービスです。
    br
    | GIGで記事を投稿すると、GitHub上のあなたのレポジトリに記事データが保存されます。
    br
    | 手元で編集した記事をGitHubにPushすると、GIGはあなたのレポジトリ内の記事を自動的に同期します。

.section.row-fluid
  .span3
    h3
      i.icon-random
      | Gitとブラウザ
    p
      | 好きなテキストエディタで編集した記事をGitから投稿出来ます。
      | Gitを全く知らなくても、ブラウザだけで使うことができます。
  .span3
    h3
      i.icon-fast-backward
      | 履歴管理
    p
      | 全ての変更がGitでバージョン管理されるため、いつでも変更の履歴を確認したり、
      | 昔の状態に戻したりできます。
  .span3
    h3
      i.icon-group
      | Social Blogging
    p
      | GitHubのCollaboratorやPull Requestを利用して、
      | 履歴を残しながらブログを共同編集することができます。
  .span3
    h3
      i.icon-edit
      | Markdown
    p
      | 記事の編集にはGitHub Flavored Markdown形式を利用し、
      | その場でプレビューを確認しながら編集できるようになる予定です...。

app/views/users/show.html.slim
ul.entries
  - entries = @user.entries
  - if entries.empty?
    p
      | まだ記事がありません
  - else
    - entries.each do |entry|
      li.entry
        = link_to [@user, entry] do
          .title
            i.icon-file-alt
            = entry.title
          .date= entry.date